import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { 
      question, 
      response, 
      metadata 
    } = body;

    if (!question || !response) {
      return NextResponse.json(
        { error: 'Question and response are required' },
        { status: 400 }
      );
    }

    // Create a unique ID for this artwork share
    const shareId = Date.now().toString(36) + Math.random().toString(36).substr(2);
    
    // For now, we'll create a simple share URL
    // In a production app, you might want to store this in a database
    const shareUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://orthoiq.vercel.app'}/share/${shareId}?${new URLSearchParams({
      question: question.substring(0, 200),
      response: response.substring(0, 300),
      art: 'true',
      ...(metadata && {
        subspecialty: metadata.subspecialty || '',
        emotion: metadata.emotionalTone || '',
        complexity: metadata.complexityLevel?.toString() || '',
        genId: metadata.generationId || ''
      })
    }).toString()}`;

    // Generate Farcaster-optimized sharing data
    const farcasterData = {
      text: `🎨 Check out this unique medical artwork generated by AI!\n\n"${question.substring(0, 120)}${question.length > 120 ? '...' : ''}"\n\n${metadata ? `🧬 ${metadata.subspecialty} | 🎯 ${metadata.emotionalTone} | ⚡ ${metadata.complexityLevel}/10` : ''}`,
      embeds: [{
        url: shareUrl,
        metadata: {
          image: `${process.env.NEXT_PUBLIC_BASE_URL || 'https://orthoiq.vercel.app'}/api/og-image?${new URLSearchParams({
            question: question.substring(0, 100),
            response: response.substring(0, 150),
            art: 'true',
            ...(metadata && {
              subspecialty: metadata.subspecialty || '',
              genId: metadata.generationId?.substring(0, 8) || ''
            })
          }).toString()}`
        }
      }]
    };

    return NextResponse.json({
      success: true,
      shareId,
      shareUrl,
      farcasterData,
      metadata: {
        question: question.substring(0, 200),
        response: response.substring(0, 300),
        artwork: metadata || {},
        timestamp: new Date().toISOString()
      }
    }, { status: 200 });

  } catch (error) {
    console.error('Error creating artwork share:', error);
    return NextResponse.json(
      { error: 'Failed to create share link' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const shareId = searchParams.get('id');
    
    if (!shareId) {
      return NextResponse.json(
        { error: 'Share ID is required' },
        { status: 400 }
      );
    }

    // In a real implementation, you'd fetch from database
    // For now, return a mock response
    return NextResponse.json({
      success: true,
      message: 'Share data would be retrieved from database',
      shareId
    }, { status: 200 });

  } catch (error) {
    console.error('Error retrieving artwork share:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve share data' },
      { status: 500 }
    );
  }
}